# Generated by Django 4.2.7 on 2023-11-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_departmentsid_departments_departmentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Departments',
            new_name='Department',
        ),
    ]
